url: http://www.atlabs.xyz/

# Site settings
title: ATLabs - Ideas for Auckland
email: test@domain.com
description: "Test description."

timezone: Pacific/Auckland
markdown: kramdown
highlighter: rouge

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/at
  - title: bitbucket 
    url: http://bitbucket.org/
  - title: github
    url: http://github.com/

# Postal address (add as many lines as necessary)
address:
  - line: 34 Drake St,
  - line: Auckland, 1010

# Build settings
markdown: kramdown
permalink: pretty